log-level: "info" # ["trace","debug","info","warn","error","fatal"]
log-db-queries: false

application-name: "social-danpalmer-me"
landing-page-user: "dan"
host: "social.danpalmer.me" # Must not change
account-domain: "danpalmer.me" # Must not change

protocol: "https"
bind-address: "0.0.0.0"
port: 8080
trusted-proxies:
  - "127.0.0.1/32"
  - "::1"

db-type: "postgres"
db-address: "social-danpalmer-me-db.internal"
db-port: 5432
db-user: "postgres"
db-password: "" # Set in $GTS_DB_PASSWORD
db-database: "social"
db-tls-mode: "disable"
db-tls-ca-cert: ""

instance-expose-peers: false
instance-expose-suspended: false
instance-expose-public-timeline: false
instance-deliver-to-shared-inboxes: true

accounts-registration-open: false
accounts-approval-required: true
accounts-reason-required: true
accounts-allow-custom-css: false

media-image-max-size: 10485760 # 10MB
media-video-max-size: 41943040 # 40MB
media-description-min-chars: 0
media-description-max-chars: 500
media-remote-cache-days: 30
media-emoji-local-max-size: 51200
media-emoji-remote-max-size: 102400 # 100KB

storage-backend: "local"
storage-local-base-path: "/gotosocial/storage"
storage-s3-endpoint: ""
storage-s3-proxy: false
storage-s3-access-key: ""
storage-s3-secret-key: ""
storage-s3-bucket: ""

statuses-max-chars: 5000
statuses-cw-max-chars: 100
statuses-poll-max-options: 6
statuses-poll-option-max-chars: 50
statuses-media-max-files: 6

letsencrypt-enabled: false
letsencrypt-port: 80
letsencrypt-cert-dir: "/gotosocial/storage/certs"
letsencrypt-email-address: ""

oidc-enabled: false
oidc-idp-name: ""
oidc-skip-verification: false
oidc-issuer: ""
oidc-client-id: ""
oidc-client-secret: ""
oidc-scopes:
  - "openid"
  - "email"
  - "profile"
  - "groups"
oidc-link-existing: false

smtp-host: "smtp.fastmail.com"
smtp-port: 465
smtp-username: "danpalmer@fastmail.fm"
smtp-password: "" # Set in $GTS_SMTP_PASSWORD
smtp-from: "social@danpalmer.me"

syslog-enabled: false
syslog-protocol: "udp"
syslog-address: "localhost:514"

advanced-cookies-samesite: "lax"
advanced-rate-limit-requests: 1000
